### ISSUE TITLE
View Collected Data in the Stats Table tab

### ISSUE THREAD

**Issue by nickGarska** [COSC481W-2024Winter/StormStats#3]
User Story
Neilo has used the app to collect information and now feels they have enough information to make useful conclusions with. Neilo wants to be able to view his information in a neat and organized manner. Neilo wants to be able to sort the data by Varity of criteria such as most encountered player, highest/lowest win rate

Persona
User of App
Feature
Database viewing
Business Value
information Access

Tasks

- [x] information should be moved from the database to the UI spreadsheet via functions, this should be done on app startup and updated as information is added to the database
- [x] information sortable (I think this is default functionality of the UI)

Acceptance Criteria

1. can view information in spreadsheet
2. information is sortable with standard spreadsheet controls.

**Comment by sjiang1** [comment]
Done with 181796178216f3f83e057c4f5eda597d248566ff
